### ISSUE TITLE
Support building with plain babel

### ISSUE THREAD

**Issue by xaviervia** [saguijs/sagui#119]
For libraries. This could be done when using sagui set up for [library](https://github.com/saguijs/sagui#library)

**Comment by pirelenito** [comment]
This might be a little more tricky to implement, specially if the user wants to load other stuff ratter than JS in the final library.

The current solution using Webpack might be a good enough general purpose solution that we might actually recommend.

**Comment by xaviervia** [comment]
Could it be done with the CLI behind a specific flag? Like adding a `--babel` in the `sagui build` in the npm build script or something. I'd still like to have this feature available since it increases sagui usefulness significantly.

While at it, it would be pretty nice to have sagui setting up the `prepublish` task as well, since all tasks involved in that would be sagui commands anyway. 

Or maybe this configuration should go to a fork project called `sagui-library` or something like that? The common functionality is big, but it might be a stretch to have a `prepublish` task in application projects. Or would it?

**Comment by xaviervia** [comment]
This no longer makes sense now that the library archetype solves library publishing completely.
