### ISSUE TITLE
Allow disabling CSS modules

### ISSUE THREAD

**Issue by tulios** [saguijs/sagui#151]
I understand the value of css modules but sometimes we want to use external styles or just keep the old approach, it would be nice to have a flag, or something else, to disable it.

Thanks for the awesome project!

**Comment by pirelenito** [comment]
It could be something like:

```js
{
  style: {
    cssModules: false
  }
}
```

Where the default value would be `true`.

**Comment by pirelenito** [comment]
Done! Fixed in #156
