### ISSUE TITLE
Idea: Create a "meta" Atom packages that install recommended Sagui packages

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#155]
Initially I think something like Linting and EditorConfig support, but we could add more stuff.

Thoughts? Do you think it is possible? Should we do the same for Sublime (I'm a sublime user)?

Some packages to consider:

- https://atom.io/packages/editorconfig
- https://github.com/gandm/language-babel
- https://github.com/AtomLinter/linter-eslint

**Comment by xaviervia** [comment]
Sagui doesn't really set up an editorconfig file, does it?

**Comment by pirelenito** [comment]
Yes it does set it up! 😂

**Comment by pirelenito** [comment]
It is out of the scope of this project. Rejecting it for now.
