### ISSUE TITLE
Add support for loading raw text files

### ISSUE THREAD

**Issue by Deschtex** [saguijs/sagui#165]
Loader: https://github.com/webpack/raw-loader

**Comment by pirelenito** [comment]
I guess we could add it, but I'm not sure how common it is to use it. Maybe we should leave it out for now?

**Comment by Deschtex** [comment]
I don't know either. It feels like something basic, though... or?

**Comment by pirelenito** [comment]
I just looked at the dependency and I have to agree with you... it is supper small and has no other dependencies, so I guess it should be fine.

Can you prepare a PR?

**Comment by Deschtex** [comment]
Will do!

**Comment by pirelenito** [comment]
Fixes on #184
