### ISSUE TITLE
Cant install sagui on windows

### ISSUE THREAD

**Issue by JJzcru** [saguijs/sagui#170]
I try to run sagui on windows 10 and says an error in the install

**Comment by pirelenito** [comment]
Hi @JJzcru,

Sagui was never tried on Windows, but we definitely want to add support.

Could you provide more information, like the error log?

**Comment by pirelenito** [comment]
We started working on it, you can follow it at  #171

**Comment by pirelenito** [comment]
Was just fixed on #171 and released in `6.1.1`.

Can you please try crating a new project and confirm that it works.

Thanks!

**Comment by pirelenito** [comment]
I would like to add that we are also running our automated tests in Windows as well, to make sure we keep the support working forever ❤️.

**Comment by pirelenito** [comment]
I'm closing the issue, let me know if you still have issues and we can re-open it. 😀
