### ISSUE TITLE
Add unofficial but trustworthy Windows builds of flow?

### ISSUE THREAD

**Issue by xaviervia** [saguijs/sagui#179]
So that we can provide type check support also on Windows.

This is a follow up of https://github.com/saguijs/sagui/pull/172#issuecomment-230816251

Currently unofficial builds exists provided by the community but we should not bundle them automatically unless we verify their signature and the way there were built. Otherwise we'll have to wait until Facebook starts providing official builds.

**Comment by pirelenito** [comment]
Official build is here! https://www.flowtype.org/blog/2016/08/01/Windows-Support.html

**Comment by xaviervia** [comment]
Let's add this to the flowtype support ASAP

**Comment by xaviervia** [comment]
Closing this and following up on https://github.com/saguijs/sagui/issues/182
