### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by npejo** [saguijs/sagui#181]
When you run `npm run test:unit:watch` if there is compilation error, it breaks the watch.

**Comment by xaviervia** [comment]
Thanks for reporting this, we should definitely fix soon.

**Comment by pirelenito** [comment]
I'm on it!

**Comment by pirelenito** [comment]
@npejo I've tried this on a fresh project and was unable to reproduce it.

**Comment by pirelenito** [comment]
We need to be more flexible on errors while running "development" actions. We are probably misusing the [NoErrorsPlugin](https://github.com/MoOx/eslint-loader#noerrorsplugin)

We should also change the linter to not "break" while running the test watcher or development server... we can show warnings but never errors. The goal is to allow experimentation.
