### ISSUE TITLE
Consider using Greenkeeper

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#198]
Automatically update the dependencies: https://greenkeeper.io/

**Comment by pirelenito** [comment]
We did a first trial, but got a lot of updates. Lets try this again at a latter point.

https://github.com/saguijs/sagui/pull/203

**Comment by xaviervia** [comment]
I like the idea of Greenkeeper, but I wonder if we should suggest them to bundle updates in bulk in a single PR per day and wait for that before using it.

**Comment by pirelenito** [comment]
I just enabled it again! Lets see how it goes.

**Comment by pirelenito** [comment]
Looking good! Lets keep it enabled for now.
