### ISSUE TITLE
Set up environment

### ISSUE THREAD

**Issue by bichotll** [saguijs/sagui#200]
First off, I'm "kinda" new with webpack. I found your project really interesting.

I wonder how I can apply this logic as I don't have access to the variable env from sagui.config.js
http://stackoverflow.com/questions/28572380/conditional-build-based-on-environment-using-webpack#answer-29851256

Otherwise, how I can load a configuration depending on the environment (dev/prod...others)?

**Comment by xaviervia** [comment]
Hi! Thanks for reaching out. The currrent way to be able to use `webpack.DefinePlugin` is that you can use the webpack "escape hatch" and configure like:

```javascript
var webpack = require('webpack')

module.exports = {
  webpack: {
    plugins: [
      new webpack.DefinePlugin({
          ENV: require(path.join(__dirname, './path-to-env-files/', env))
      })
    ]
  }
}
```

The escape hatch is documented in https://github.com/saguijs/sagui#webpack

Hope this helps, if you have more questions feel free =)

**Comment by pirelenito** [comment]
I'm considering this closed. @bichotll please ping us if you still need some help.
