### ISSUE TITLE
Add a default coverage threshold to break the test runner

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#202]
Tests should break if coverage is bellow a threshold.

https://github.com/karma-runner/karma-coverage/blob/master/docs/configuration.md#check

What should be the default values, how should allow this to be configured?

**Comment by cpapazaf** [comment]
What if this karma config part gets exposed as is?

**Comment by pirelenito** [comment]
I think this is too harsh. Rejecting for now.
