### ISSUE TITLE
Refusing to install sagui as a dependency of itself

### ISSUE THREAD

**Issue by nelsongustavo** [saguijs/sagui#208]
Hi guys i'm getting this error when i run: "npm install --save-dev sagui"

npm ERR! Darwin 15.6.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save-dev" "sagui"
npm ERR! node v0.10.20
npm ERR! npm  v3.10.7
npm ERR! code ENOSELF

npm ERR! Refusing to install sagui as a dependency of itself

**Comment by pirelenito** [comment]
Hi @nelsongustavo, can you share more information related to where you are running the command? Is this a new NPM project?

I also noticed that you are using a very old version on Node (0.10.20). Could you try updating to the newest LTS release (4.5.0)?

**Comment by nelsongustavo** [comment]
Hi @pirelenito I just created a new folder, run `npm init -y ` and `npm install --save-dev sagui`.

I just install the newest LTS release (4.5.0) and the problem remains.

npm WARN install Refusing to install sagui as a dependency of itself

Thank you for the fast reply.

**Comment by pirelenito** [comment]
I think I know the problem. What is the folder name you have created? Did you create a `sagui` folder to try it out? Then it would look like to npm that you are installing `sagui` into `sagui`.

If that is the case, can you try creating a folder with a different name?

**Comment by nelsongustavo** [comment]
@pirelenito Sorry My mistake, I have created sagui folder, creating another folder solve the problem.

Thanks for the help and sorry for that.

**Comment by pirelenito** [comment]
No worries! I'm glad I could help.
