### ISSUE TITLE
Remove default Sinon support from Karma

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#209]
Currently we have installed `karma-sinon` which setups a global `sinon` object while running the tests with Karma.

For v7, I vote we deprecate this and leave it as a user option. It is much better to have it explicitly required whenever someone wants to use it anyway:

```js
import sinon from 'sinon'
```

**Comment by xaviervia** [comment]
Fully agree. 

On a more opinionated note, Sinon loses relevance as code moves to pure functions (I found myself using it less and less with React and Redux). I think it makes sense to phase it out from being a default.

**Comment by xaviervia** [comment]
Done for upcoming v7 in #243
