### ISSUE TITLE
Karma tests are being run twice

### ISSUE THREAD

**Issue by cskeppstedt** [saguijs/sagui#250]
When running `npm run test:unit:watch` and you modify a file, the tests seem to be run twice.

Found this that might be related:
- https://github.com/webpack/karma-webpack/issues/44
- https://github.com/davezuko/react-redux-starter-kit/pull/246 (from https://pracucci.com/avoid-karma-tests-run-twice-on-autowatch.html)

This is easy to reproduce on mac os x, can check linux later and see if it's platform-dependant.

**Comment by pirelenito** [comment]
@cskeppstedt this was fixed as part of the `7.1.1` release. Let us know if it works for you.

Thanks for reporting it!
