### ISSUE TITLE
Use always same id for root div in default index.html

### ISSUE THREAD

**Issue by xaviervia** [saguijs/sagui#256]
The reason: right now it's not possible to copy paste an example of an `index.js` without updating the part that references the div. It would be extremely useful in guides for other tools to be able to say:

> Just install Sagui and when it's done copy paste this into the `src/index.js`:
>
> ```javascript
> // Some JS example that ends with
> render( <Component />, document.getElementById('root'))
> ```

**Comment by pirelenito** [comment]
Good point!
