### ISSUE TITLE
cross-env: command not found

### ISSUE THREAD

**Issue by ChristerGustavsson** [saguijs/sagui#263]
creating a new sagui project and attempting to run the tests gives me this:

``` bash
$ yarn test
yarn test v0.16.0
$ npm run test:lint && npm run test:typecheck && npm run test:unit

> tmp@1.0.0 test:lint /Users/christer.gustavsson/Projects/stash/META/tmp
> sagui lint

🐵  Sagui Lint completed without errors.

> tmp@1.0.0 test:typecheck /Users/christer.gustavsson/Projects/stash/META/tmp
> sagui typecheck

🐵  Sagui Type check completed without errors

> tmp@1.0.0 test:unit /Users/christer.gustavsson/Projects/stash/META/tmp
> cross-env NODE_ENV=test sagui test

sh: cross-env: command not found
```

**Comment by xaviervia** [comment]
Oh yarn!

As a quick feedback: it will work with npm. 

But we should fix this soon.

**Comment by pirelenito** [comment]
Hi @ChristerGustavsson, we are finally fixing this is the upcoming v8 release.

You can start testing if you want. The release is fairly stable: `v8.0.0-rc.3`

Let us know if you have any issue.

Sorry for the delay!

**Comment by pirelenito** [comment]
Fixed and released in v8 which is currently the latest stable.
