### ISSUE TITLE
Automatically install NPM dependencies

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#27]
https://github.com/ericclemmons/npm-install-webpack-plugin

**Comment by pirelenito** [comment]
I'm not sure this is a good idea.

**Comment by pirelenito** [comment]
I actually think this could be the default behavior, but could be easily disabled with a configuration flag.

We could even warn the user about this behavior on first start. I think it is great for beginners!

**Comment by pirelenito** [comment]
We can add a flag in the configuration file and a option in the CLI to auto-install stuff.

**Comment by xaviervia** [comment]
I like this 👍

**Comment by pirelenito** [comment]
Our first attempt wasn't very successful. Rejecting for now.
