### ISSUE TITLE
Trying to run yarn build fails because of eslint webpack loader

### ISSUE THREAD

**Issue by thezanke** [saguijs/sagui#306]
When I try to run `yarn build` I get the following:
```
🐵  Sagui Setting NODE_ENV=development
🐵  Sagui Build failed.
(undefined) Loader /path/to/project/node_modules/sagui/node_modules/eslint/lib/api.js didn't return a function
error Command failed with exit code 1.
```

This is due to a bug in the webpack loader only using "eslint" instead of "eslint-loader". To patch this locally in my project I added the following to my `sagui.config.js`:

```
module.exports = {
  ...
  webpack: {
    module: {
      preLoaders: [
        {
          test: /\.(jsx?|es6)$/,
          loader: 'eslint-loader',
          exclude: /node_modules/
        }
      ]
    }
  }
}
```

More info on bug [here](https://github.com/survivejs/react/issues/3), as well as other sources findable through Google.

**Comment by thezanke** [comment]
It's worth mentioning, for reproducibility, that I am using the "react-app" eslint config. Here's my `.eslintrc`:
```
{
  "extends": "react-app"
}
```

This required a peerDependency of `eslint@^3.8.1` which I then added as a devDependency. Only once I add the eslint package does the problem occur.

**Comment by urrvesh** [comment]
Please install **eslint-loader** using **npm i eslint-loader** or **yarn add eslint-loader**
