### ISSUE TITLE
Should we start thinking about adoting transform-es2015-modules-commonjs?

### ISSUE THREAD

**Issue by xaviervia** [saguijs/sagui#309]
http://www.2ality.com/2017/01/babel-esm-spec-mode.html

One specially important takeaway:

![screen shot 2017-01-27 at 13 13 57](https://cloud.githubusercontent.com/assets/381614/22370745/3d8b2ce6-e493-11e6-9a21-9d799216e75c.png)

The problem is of course that this will break existing CommonJS imports that deconstruct, but given that Babel is currently not following specification at some point the whole community will have to bite the bullet anyway.

I don’t think there is a rush to do this, I wanted to start the discussion.

**Comment by pirelenito** [comment]
Is this still relevant?

**Comment by xaviervia** [comment]
Nope.
