### ISSUE TITLE
Add support for flow type check?

### ISSUE THREAD

**Issue by xaviervia** [saguijs/sagui#33]
Wdyt? https://github.com/gaearon/flowcheck-loader

**Comment by pirelenito** [comment]
I don't plan to have it as a default internally.

But [3.0.0](https://github.com/pirelenito/sagui/releases/tag/v3.0.0) has just been released which adds support for [custom webpack configurations](https://github.com/pirelenito/sagui#custom-webpack-and-karma-config).

Does that work for you?

**Comment by xaviervia** [comment]
Sure! I was half-asking what your impression on Flow is, given that it feels that it might work together pretty naturally with the rest of the stack. But of course, just adding it as an extension works as well.

**Comment by pirelenito** [comment]
I don't have a strong opinion yet, haven't tried it yet to be sure. I'll give it a go externally in some projects and consider it for the future.

Thanks :)

**Comment by xaviervia** [comment]
After some experience with it my impression is that adding it would be pretty cheap for sagui, since the standard approach to flow is for it to only work on files that start with `// @flow`. That means that consumers not interested in it can ignore it with no consequence–and flow-bin is not the heaviest dependency around (certainly pales compared to phantomjs). Another argument for it that I think can work is that flow is at this point is part of the stack that Sagui is offering.

That said, I'll give at try at doing it as a PR myself, since I showed the most interest. Only question, what dev branch should I point to? v5? v6? v4?

Thanks!

**Comment by xaviervia** [comment]
I'm closing this since we are doing it. Will follow up in https://github.com/saguijs/sagui/issues/182
