### ISSUE TITLE
Should we move to prettier?

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#336]
With the recent announcement of [Prettier 1.0](http://jlongster.com/prettier-1.0) we can finally disable semicolons!

I've tried the formatting locally and it seems to be outputting a nice result.

But, if we go in this direction, how would we make it simple for our users? Should we setup the git-hooks? Should we still have a linter?

I guess we could stick to StandardJS for the upcoming v9 release, and aim for a v10 if we feel like it is the way to go.

**Comment by pirelenito** [comment]
I guess we could have too scripts:

- `npm run lint` that would do the normal static analysis (prettier and standard) and show any errors
- `npm run lint:fix` that would apply the prettier fixes

**Comment by pirelenito** [comment]
We are moving in this direction. So I'll create other issues with the remaining work.

**Comment by xaviervia** [comment]
Sorry I didn't answer before. I think this is great
