### ISSUE TITLE
CSS modules hash collision in v9

### ISSUE THREAD

**Issue by npejo** [saguijs/sagui#338]
https://github.com/postcss/postcss-loader/issues/129

**Comment by pirelenito** [comment]
There might be an alternative https://github.com/postcss/postcss-loader#css-modules

> use postcss-modules plugin instead of css-loader

**Comment by pirelenito** [comment]
It looks like it is not only Webpack related: https://github.com/css-modules/postcss-modules/issues/32

**Comment by pirelenito** [comment]
This was finally the solution: https://github.com/webpack-contrib/css-loader/issues/413#issuecomment-283944881

Currently working in a PR!
