### ISSUE TITLE
yarn test:lint passes anyways in 9.0.0-rc.16

### ISSUE THREAD

**Issue by abdulhannanali** [saguijs/sagui#358]
### Summary

I want to report a bug I found in v9.0.0-rc.16 while checking out 
[react-context-props](https://github.com/xaviervia/react-context-props) which just adopted it.

yarn test:lint exits with code 0 and shows as though there are no lint errors within the repository, although there are. 

### Reproduction of issue

Created a minimal bug reproduction repo, specifically check `src/index.js` which contains errors, according to the rules specified in sagui, but `yarn test:lint` still passes with exit code `0`

Link: https://github.com/abdulhannanali/sagui-bug-eslint

**Comment by pirelenito** [comment]
Thank you so much for reporting it. I have a PR with a fix WIP.

**Comment by pirelenito** [comment]
I've released the fix as part of https://github.com/saguijs/sagui/releases/tag/v9.0.0-rc.17

But we should also try to get #361 done soon.
