### ISSUE TITLE
Fix the support for `inject-loader` in v9

### ISSUE THREAD

**Issue by npejo** [saguijs/sagui#364]
`inject-loader` does not support ES6 modules. To be able to run unit tests that are using this loader we need to have transpiled modules to `commonjs`.

Also the eslint rule `import/no-webpack-loader-syntax` should be disabled to allow imports as `'inject-loader!./path/to/module`

**Comment by xaviervia** [comment]
I believe you @npejo and @pirelenito have some links to a discussion in the Webpack community about how to solve this issue, would you mind pasting it here for context? I would like to know for sure that Webpack is providing support for `inject-loader` before we move in any direction.
