### ISSUE TITLE
Enable transpile cache for babel-loader

### ISSUE THREAD

**Issue by deepsweet** [saguijs/sagui#381]
https://github.com/babel/babel-loader#options

>`cacheDirectory`: Default false. When set, the given directory will be used to cache the results of the loader. Future webpack builds will attempt to read from the cache to avoid needing to run the potentially expensive Babel recompilation process on each run. If the value is blank (`loader: 'babel-loader?cacheDirectory'`) or `true` (`loader: babel-loader?cacheDirectory=true`) the loader will use the default cache directory in znode_modules/.cache/babel-loaderz or fallback to the default OS temporary file directory if no znode_modulesz folder could be found in any root directory.

It's _much_ faster with this option especially when you have dozens of files.

[Here](https://github.com/saguijs/sagui/blob/v10/src/configure-webpack/loaders/javascript.js) it looks like it's impossible to pass loader options from `sagui.config`.

**Comment by pirelenito** [comment]
That sounds interesting. We should try this out!

**Comment by deepsweet** [comment]
Definitely, in my experience webpack startup is up to 1.5 times faster when cache is hot on huge codebase.

**Comment by pirelenito** [comment]
Can you push a PR against the v11 branch with some benchmark comparisons? ❤️

**Comment by pirelenito** [comment]
Done and released in v11
