### ISSUE TITLE
Warn users if they have case mismatch in paths

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#390]
> enforces the entire path of all required modules match the exact case of the actual path on disk. Using this plugin helps alleviate cases where developers working on OSX, which does not follow strict path case sensitivity, will cause conflicts with other developers or build boxes running other operating systems which require correctly cased paths.

https://github.com/Urthen/case-sensitive-paths-webpack-plugin

**Comment by xaviervia** [comment]
Nice :)
