### ISSUE TITLE
Sagui loads karma-firefox-launcher even when it is not used

### ISSUE THREAD

**Issue by hex0cter** [saguijs/sagui#394]
When I test IE on windows, karma-firefox-launcher is somehow loaded. This is usually not a big deal as long as it works. However at the moment the plugin is broken on windows due to this: https://github.com/karma-runner/karma-firefox-launcher/pull/74

While is plugin is plugin is broken, I am not able to run the IE test on windows. So the question is, why is karma-firefox-launcher executed while I don't care about Firefox at all?

**Comment by pirelenito** [comment]
The plugin is still loaded automatically by Karma, that is why you see the issue.

We could try be specific about which plugins to load, but that would require us in Sagui to do the parsing of the browsers list for example.

I would say it is much better to help/wait to get the Firefox plugin issue fixed.

**Comment by hex0cter** [comment]
OK. I am going to close the ticket in that case.

**Comment by pirelenito** [comment]
We might still need to update the `karma-firefox-launcher` plugin in Sagui once they fix the problem. If that turns to be needed, feel free to reopen this issue or submit a PR with the version bump.

**Comment by hex0cter** [comment]
That sounds good. I will keep an eye on the original bug.
