### ISSUE TITLE
Running karma-plugins

### ISSUE THREAD

**Issue by cskeppstedt** [saguijs/sagui#50]
Let's say I want to add a Karma-plugin, e.g. `karma-junit-reporter`. I would install in my project:

    npm install --save-dev karma-junit-reporter

I would include the configuration in sagui.config.js:

    karmaConfig: {
      junitReporter: {
        ...
      },
      reporters: ['junit']
    }

However, when running `npm test`, Karma will complain that it cannot find the reporter:

    04 03 2016 10:50:41.978:WARN [reporter]: Can not load "junit", it is not registered!
      Perhaps you are missing some plugin?

Copying the plugin into the sagui _node_modules_ folder solves the issue:

    cp -r node_modules/karma-junit-reporter node_modules/sagui/node_modules/

Is there anyway that karma-plugins in the local _node_modules_ could be resolved?

I realize that this starts to approach the "Nice framework! but I want it to do this super weird thing"-category of issues. Just food for thought on adding more flexibility when consuming sagui.

**Comment by pirelenito** [comment]
I'll think about a solution during this weekend. 

A quick fix for it is to use NPM 3, since it uses a flat directory structure by default, you won't have this issue.

**Comment by cskeppstedt** [comment]
Cool! I'll try to upgrade my pipeline to a newer node/npm anyway, so this is not a blocker for me at least. Realized that I either had to do that, or add deduplication to webpack, cause my build was including multiple lodashes :) So, two birds with one stone.

**Comment by pirelenito** [comment]
I'm considering this fixed. @cskeppstedt let me know if you have any more issues. 😄
