### ISSUE TITLE
Add native Enzyme support

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#53]
Should we have Enzyme installed by default? If not, should we have its configuration already in-place?

http://airbnb.io/enzyme/docs/guides/webpack.html

**Comment by pirelenito** [comment]
We might need to do:

```

**Comment by pirelenito** [comment]
It requires different configurations depending on which version of React you use. Given it is a hack... unfortunately it is better to leave it in user-land setup.

**Comment by pirelenito** [comment]
We could actually detect the installed version of React and properly setup the integration with Enzyme. Thoughts?

**Comment by xaviervia** [comment]
How would you detect the version of React?

**Comment by pirelenito** [comment]
We can just support React 15, add a flag to disable it if someone wants to use React 0.14.

**Comment by pirelenito** [comment]
Not going to do this.
