### ISSUE TITLE
Review the Library implementation

### ISSUE THREAD

**Issue by pirelenito** [saguijs/sagui#56]
The name should be a valid JavaScript symbol in the cammel case format.

If a name with dashes is provided, the compiled code will be incorrect, throwing the error:

```
Uncaught SyntaxError: Unexpected token -
```

**Comment by Deschtex** [comment]
How would one verify this?

**Comment by xaviervia** [comment]
I think it would be also nice to clarify in the README how the library name is actually used by Sagui. My understanding is that the `index.js` will be picked up and packaged, but how will the name be used then?

**Comment by pirelenito** [comment]
We can actually change this ticket to review the library feature, we might not need the name anymore.

**Comment by pirelenito** [comment]
The name is indeed not required, so my suggestion is that we make it similar to how pages works.

We change the configuration to be:

```js
{
  libraries: ['index', 'other-index', 'whatever']
}
```

And it points to the entry point of a library... and we can add as many libraries as we want.

Each library gets build to `dist/name` as well to make it simple.

If everyone agrees, then I can prepare a PR.

**Comment by pirelenito** [comment]
Btw, I'll want to merge #140 before I can work on this 😬
